[package]
name = "simple_http"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = { version = "0.12.1" }

tiny_http = { version = "0.12.0"}

tokio = { version = "1.26.0", features = ["full"]}
