[package]
name = "simple_http"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = { version = "0.12.0"}

[dev-dependencies]
sha-1 = "0.10.1"
rustc-serialize = "0.3.24"